use crate::models::{CharacterRecord, PersonalityProfile, PersonalityTraits};

pub const AVAILABLE_AI_MODELS: &[&str] = &[
  "claude-3-5-sonnet-20241022",
  "claude-haiku-4-5-20251001-thinking",
  "claude-opus-4-20250514",
  "claude-sonnet-4-20250514-thinking",
  "claude-sonnet-4-5",
  "deepseek-chat",
  "deepseek-r1",
  "deepseek-r1-0528",
  "deepseek-v3",
  "deepseek-v3-1-think-250821",
  "deepseek-v3.1-fast",
  "deepseek-v3.2-exp-thinking",
  "ERNIE-Tiny-8K",
  "gemini-2.5-flash",
  "gemini-2.5-pro",
  "gpt-4-0613",
  "gpt-4-vision-preview",
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-4.1-mini-2025-04-14",
  "gpt-4.1-nano",
  "gpt-4o",
  "gpt-4o-mini",
  "gpt-5",
  "gpt-5-all",
  "gpt-5.1-chat-latest",
  "gpt-5.3-chat-latest",
  "grok-4.1",
  "grok-4.1-fast",
  "llama-3.2-1b-instruct",
  "o1",
  "o3",
  "o4-mini-all",
  "qvq-max",
  "qwen-turbo-2025-07-15",
  "qwen3-coder-plus",
  "qwen3-max",
];

pub const LEGACY_MIGRATED_MODULES: &[&str] = &["config", "auth", "characters"];

pub fn seeded_characters() -> Vec<CharacterRecord> {
  vec![
    build_character(
      "char_lawyer",
      "Wang Jianguo",
      "lawyer-friend",
      "expert",
      vec!["law".into()],
      "Practicing lawyer focused on contract disputes, labor law, and company law.",
      "Grounded, practical, and occasionally dryly funny.",
      "normal",
      1,
      2,
    ),
    build_character(
      "char_doctor",
      "Li Xiaomeng",
      "doctor-colleague",
      "expert",
      vec!["medicine".into()],
      "Internal medicine doctor who likes practical health advice and calm check-ins.",
      "Warm, attentive, and quietly protective.",
      "normal",
      1,
      1,
    ),
    build_character(
      "char_tech",
      "Chen Gong",
      "engineer-friend",
      "expert",
      vec!["tech".into()],
      "Full-stack engineer who prefers short, precise answers and code-first explanations.",
      "Dry humor, high signal, low fluff.",
      "high",
      2,
      3,
    ),
    build_character(
      "char_roommate",
      "Xiao Zhao",
      "college-roommate",
      "friend",
      vec!["general".into()],
      "Talkative college roommate energy with strong loyalty once things matter.",
      "Loud, warm, and genuinely dependable.",
      "high",
      3,
      4,
    ),
  ]
}

fn build_character(
  id: &str,
  name: &str,
  relationship: &str,
  relationship_type: &str,
  expert_domains: Vec<String>,
  bio: &str,
  emotional_tone: &str,
  activity_frequency: &str,
  moments_frequency: i32,
  feed_frequency: i32,
) -> CharacterRecord {
  CharacterRecord {
    id: id.into(),
    name: name.into(),
    avatar: "avatar".into(),
    relationship: relationship.into(),
    relationship_type: relationship_type.into(),
    personality: Some(emotional_tone.into()),
    bio: bio.into(),
    is_online: true,
    is_template: true,
    expert_domains: expert_domains.clone(),
    profile: PersonalityProfile {
      character_id: id.into(),
      name: name.into(),
      relationship: relationship.into(),
      expert_domains,
      base_prompt: None,
      traits: PersonalityTraits {
        speech_patterns: Vec::new(),
        catchphrases: Vec::new(),
        topics_of_interest: Vec::new(),
        emotional_tone: emotional_tone.into(),
        response_length: "medium".into(),
        emoji_usage: "occasional".into(),
      },
      memory_summary: String::new(),
      system_prompt: None,
      identity: None,
      behavioral_patterns: None,
      cognitive_boundaries: None,
      reasoning_config: None,
      memory: None,
    },
    activity_frequency: activity_frequency.into(),
    moments_frequency,
    feed_frequency,
    active_hours_start: Some(9),
    active_hours_end: Some(22),
    trigger_scenes: None,
    intimacy_level: 0,
    last_active_at: None,
    ai_relationships: None,
    current_status: None,
    current_activity: None,
  }
}
